language: android
sudo: required
android:
  components:
    - tools
    - platform-tools
    #- build-tools-28.0.3
    #- android-28

jdk: oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

install:
  - echo $ANDROID_HOME
  - mkdir -p $ANDROID_HOME/licenses
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license
  - cat $ANDROID_HOME/licenses/android-sdk-license

before_script:
  - travis_wait .ci/preInstall.sh

script:
  - gradle --version
  - WRAPPER=$(find . -type f -executable -name gradlew -print -quit)
  - $WRAPPER components # Dummy call to trigger Android SDK auto-download.
  #temporory fix for kotlin-sample build
  - cd kotlin-sample && gradlew build && cd ..
  - $WRAPPER buildAll
